#!/usr/bin/env python
from __future__ import print_function

import json
import sys
import hashlib


def anonymize_str(texts):
    result = []
    for text in texts.split():
        prefix = text[:6]
        prefix_md5 = hashlib.md5(prefix).hexdigest()[:4]
        md5 = hashlib.md5(text).hexdigest()[:10]
        if text.startswith("dev"):
            result.append("-".join(["devel", prefix_md5, md5]))
            continue
        if text.startswith("tuv"):
            result.append("-".join(["testing", prefix_md5, md5]))
            continue
        result.append("-".join([prefix_md5, md5]))
    return " ".join(result)


def anonymize(obj):
    for key in ["source", "target", "name", "id"]:
        if key in obj:
            obj[key] = anonymize_str(obj[key])
    return obj


if __name__ == "__main__":
    data = json.load(sys.stdin)

    for link in data["links"]:
        anonymize(link)

    new_ordered_nodes = []
    for node in data["nodes_ordered"]:
        new_ordered_nodes.append(anonymize_str(node))
    data["nodes_ordered"] = new_ordered_nodes

    new_nodes = {}
    for key, value in data["nodes"].items():
        new_key = anonymize_str(key)
        new_nodes[new_key] = anonymize(value)
    data["nodes"] = new_nodes

    print(json.dumps(data, indent=4))
