#!/usr/bin/env python
"""
Usage:
    rawdata2hive TIMESTAMP
"""
from __future__ import print_function

import glob
import json
import os

from docopt import docopt

from netkraken_analyzer import add_node, dumps


arguments = docopt(__doc__)

timestamp = arguments["TIMESTAMP"]

links = []
nodes = {}
for filename in glob.glob(os.path.join("rawdata", "*", "final", timestamp)):
    with open(filename) as f:
        data = json.load(f)
        for connection, count in data.items():
            source, target, protocol = connection.split()
            link = {
                "id": "%s %s" % (source, target),
                "protocol": protocol,
                "source": source,
                "target": target,
                "count": count,
            }
            links.append(link)

            add_node(source, nodes)
            add_node(target, nodes)

print(dumps(links, nodes))
