#!/usr/bin/env python
"""
Usage:
    rawdata2hive TIMESTAMP
"""
from __future__ import print_function

import json

from docopt import docopt

from netkraken_analyzer import calc_nodes_and_links


arguments = docopt(__doc__)
timestamp = arguments["TIMESTAMP"]

print(json.dumps(calc_nodes_and_links(timestamp)))
